# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 500mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mohamed
      POSTGRES_USER: postgres
      POSTGRES_DB: omra
